name: gleam_version

description: get gleam version

inputs:
  fallback-version:
    description: fallback gleam version
    required: false

runs:
  using: composite
  steps:
    - uses: aslilac/setup@v1
      with:
        archives: |
          https://mckayla.cloud/tomlq-linux-x64.tar.gz
    - name: Get raw version
      id: raw-version
      shell: bash
      run: |
        tomlq gleam -f gleam.toml
        echo "VERSION_RAW=$(tomlq gleam -f gleam.toml)" >> "$GITHUB_OUTPUT"
    - name: Get version
      id: version
      shell: bash
      env:
        RAW_VERSION: ${{ steps.raw-version.outputs.VERSION_RAW }}
      run: |
        echo "Raw version is: $RAW_VERSION"
