name: gleam_version

description: get gleam version

inputs:
  fallback-version:
    description: fallback gleam version
    required: false

runs:
  using: composite
  steps:
    - uses: aslilac/setup@v1
      with:
        archives: |
          https://mckayla.cloud/tomlq-linux-x64.tar.gz
    - name: Get raw version
      id: raw-version
      shell: bash
      run: |
        echo "VERSION_RAW=$(tomlq gleam -f gleam.toml)" >> "$GITHUB_OUTPUT"
    - name: Get version
      id: gleam-version
      shell: bash
      env:
        RAW_VERSION: ${{ steps.raw-version.outputs.VERSION_RAW }}
      run: |
        echo "Raw version is: $RAW_VERSION"
        echo $RAW_VERSION | sed -nE "s/^.*([[:digit:]]+\.[[:digit:]]+(\.[[:digit:]]+))/\1/p" > gleam_version.txt
        echo "GLEAM_VERSION=$(cat gleam_version.txt)" >> "$GITHUB_OUTPUT"
    - name: Print Version
      shell: bash
      env:
        GLEAM_VERSION: ${{ steps.gleam-version.outputs.GLEAM_VERSION }}
      run: |
        echo "Gleam version: $GLEAM_VERSION"
