name: ci

on:
  push:
    branches:
      - "main"
    tags:
      - v**
  pull_request:

jobs:
  get_version:
    runs-on: ubuntu-latest
    outputs:
      gleam-version: ${{ steps.gleam-version.outputs.gleam-version }}
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Get Gleam version
        id: gleam-version
        run:
          GLEAM_VERSION = "$(cat .tool-versions | sed -E 's/gleam (.+)/\1/')"
          echo "gleam-version=$GLEAM_VERSION" >> $GITHUB_OUTPUT
        id: gleam-version
  test:
    runs-on: ubuntu-latest
    needs: get_version
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: ./.github/actions/test
        with:
          gleam-version: ${{ needs.get_version.outputs.gleam-version }}
  publish:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    needs:
      - test
      - get_version
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: ./.github/actions/publish
        with:
          gleam-version: ${{ needs.get_version.outputs.gleam-version }}
          hexpm-username: ${{ secrets.HEXPM_USER }}
          hexpm-password: ${{ secrets.HEXPM_PASS }}
