name: ci

on:
  push:
  pull_request:

jobs:
  get_version:
    runs-on: ubuntu-latest
    outputs:
      gleam-version: ${{ steps.gleam-version.outputs.gleam-version }}
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: johnbjrk/gleam-version@v1-rc1
        id: gleam-version
        with:
          fallback-version: ${{ vars.GLEAM_VERSION }}
  test:
    runs-on: ubuntu-latest
    needs: get_version
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: ./.github/actions/test
        with:
          gleam-version: ${{ needs.get_version.outputs.gleam-version }}
  # publish:
  #   if: ${{ startsWith(github.ref, 'refs/tags/v') }}
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v3.2.0
  #     - uses: ./.github/actions/publish
  #       with:
  #         gleam-version: ${{ vars.GLEAM_VERSION }}
  #         hexpm-username: ${{ secrets.HEXPM_USER }}
  #         hexpm-password: ${{ secrets.HEXPM_PASS }}
