name: ci

on:
  push:
  pull_request:

jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: ./.github/actions/gleam_version
        id: gleam-version
        # with:
        #   fallback-version: ${{ vars.GLEAM_VERSION }}
      - run: |
          echo "GLEAM VERSION: $GLEAM_VERSION"
        env:
          GLEAM_VERSION: ${{ steps.gleam-version.outputs.gleam-version}}
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3.2.0
  #     - uses: ./.github/actions/test
  #       with:
  #         gleam-version: ${{ vars.GLEAM_VERSION }}
  # publish:
  #   if: ${{ startsWith(github.ref, 'refs/tags/v') }}
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v3.2.0
  #     - uses: ./.github/actions/publish
  #       with:
  #         gleam-version: ${{ vars.GLEAM_VERSION }}
  #         hexpm-username: ${{ secrets.HEXPM_USER }}
  #         hexpm-password: ${{ secrets.HEXPM_PASS }}
